package it.unipd.dei.esp.whatsapd.repository

import androidx.annotation.WorkerThread
import it.unipd.dei.esp.whatsapd.repository.database.Poi
import it.unipd.dei.esp.whatsapd.repository.database.PoiDao
import it.unipd.dei.esp.whatsapd.repository.database.Review
import it.unipd.dei.esp.whatsapd.repository.database.ReviewDao
import kotlinx.coroutines.flow.Flow

/**
 * Defines methods to uniformly access data.
 */
class PoiReviewRepository(
	private val poiDao: PoiDao, private val reviewDao: ReviewDao
) {

// PoiDao
	
	/**
	 * All [Poi]s contained in the database without a specific order.
	 */
	val allPoi: Flow<List<Poi>> = poiDao.getAllPois()
	
	/**
	 * All [Poi]s in alphabetical order contained in the database.
	 */
	val allPoiAlphabetized: Flow<List<Poi>> = poiDao.getAllPoisAlphabetized()
	
	/**
	 * Alphabetical ordered [Poi]s with favourite = true.
	 */
	val favouritePoiAlphabetized: Flow<List<Poi>> = poiDao.getFavouritePoisAlphabetized()
	
	/**
	 * Searches [searchedName] inside the names of the [Poi]s in the database.
	 * Capitalization is ignored.
	 */
	fun getPoisByNameAlphabetized(searchedName: String): Flow<List<Poi>> {
		return poiDao.getPoisByNameAlphabetized(searchedName)
	}
	
	/**
	 * Returns the [Poi] (if it exists) whose name corresponds to [searchedName].
	 */
	fun getPoiByName(searchedName: String): Flow<Poi> {
		return poiDao.getPoiByName(searchedName)
	}
	
	/**
	 * Can only be called inside a worker thread. Sets the value of favourite attribute for the
	 * [Poi] with name [poiName]. If the name is wrong nothing happens.
	 */
	@WorkerThread
	suspend fun updateFavourite(poiName: String, newFavouriteValue: Boolean) {
		poiDao.updateFavourite(poiName, newFavouriteValue)
	}
	
	/**
	 * Can only be called inside a worker thread, inserts [poi] in the database, if conflict happen the insertion is ignored.
	 */
	@WorkerThread
	suspend fun insert(poi: Poi) {
		poiDao.insert(poi)
	}

// ReviewDao
	
	/**
	 * Returns [Review]s of [Poi] with id [poiName] in decreasing rating order.
	 * [poiName] must match an existing [Poi].
	 */
	fun getAllReviewsOfPoiByRating(poiName: String): Flow<List<Review>> {
		return reviewDao.getAllReviewsOfPoiByRating(poiName)
	}
	
	/**
	 * Can only be called inside a worker thread, inserts [review] in the database. Conflicts
	 * shouldn't happen because the primary key is autogenerated but if conflict happen the
	 * insertion is ignored.
	 */
	@WorkerThread
	suspend fun insert(review: Review) {
		reviewDao.insert(review)
	}
	
}
