package it.unipd.dei.esp.whatsapd.repository.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Defines the table "Review" in the database where each entry represents a different [Review].
 *
 * The primary key [id] is autogenerated and should not be passed it in the constructor as this could
 * lead to conflicts.
 *
 * ```@Entity``` annotation is needed to provide information for the foreign key:
 *  - ```parentColumns``` is the name of the column of the other table ("```Poi.name```")
 *  - ```childColumns``` is the name of the column of this table ("```Review.poi```")
 *  - ```onDelete CASCADE``` means that when a [Poi] is deleted, all its [Review]s will be deleted
 */
@Entity(
	tableName = "review_table", foreignKeys = [ForeignKey(
		entity = Poi::class,
		parentColumns = ["name"],
		childColumns = ["poi"],
		onDelete = ForeignKey.CASCADE
	)]
)
class Review(
	@ColumnInfo(name = "username") val username: String,
	@ColumnInfo(name = "poi") val poi: String,
	@ColumnInfo(name = "rating") val rating: Byte,
	@ColumnInfo(name = "text") val text: String,
	@ColumnInfo(name = "date") val date: Date = Date(),
	@PrimaryKey(autoGenerate = true) val id: Long = 0
)
